require("core.plugin_config.catppuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.mason")
require("core.plugin_config.lspconfig")
require("core.plugin_config.tabs")
require("core.plugin_config.nvim-ts-autotag")
require("core.plugin_config.nvim-surround")
require("core.plugin_config.harpoon")
-- require("core.plugin_config.auto-suggest")
